actor_system_config:
  batch_executor: 2
  executor:
  - {name: System, spin_threshold: '1', threads: 9, type: BASIC}
  - {name: User, spin_threshold: '1', threads: 16, type: BASIC}
  - {name: Batch, spin_threshold: '1', threads: 7, type: BASIC}
  - {name: IO, threads: 1, type: IO}
  - {name: IC, spin_threshold: '10', threads: 3, time_per_mailbox_micro_secs: 100,
    type: BASIC}
  io_executor: 3
  scheduler: {progress_threshold: '10000', resolution: '64', spin_threshold: '0'}
  service_executor:
  - {executor_id: 4, service_name: Interconnect}
  sys_executor: 0
  user_executor: 1
blob_storage_config:
  service_set:
    availability_domains: ['1']
    groups:
    - erasure_species: 0
      group_generation: 1
      group_id: 0
      rings:
      - fail_domains:
        - vdisk_locations:
          - {node_id: 1, path: data/pdisk-ssd.data, pdisk_category: '1', pdisk_guid: '16684173266925138728',
            pdisk_id: 1}
bootstrap_config: {}
channel_profile_config:
  profile:
  - channel:
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    profile_id: 0
  - channel:
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    - {erasure_species: none, pdisk_category: '1', storage_pool_kind: ssd, vdisk_category: Default}
    profile_id: 1
domains_config:
  disable_builtin_security: true
  domain:
  - domain_id: 1
    name: Root
    plan_resolution: '10'
    scheme_root: '72075186232723360'
    ssid: [1]
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: '1'
        erasure_species: none
        kind: ssd
        pdisk_filter:
        - property:
          - {type: SSD}
        vdisk_kind: Default
    - kind: rot
      pool_config:
        box_id: '1'
        erasure_species: none
        kind: rot
        pdisk_filter:
        - property:
          - {type: ROT}
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [1]
      nto_select: 1
    ssid: 1
dynamic_nameservice_config: {max_static_node_id: 1000}
grpc_config:
  grpc_memory_quota_bytes: '1073741824'
  host: '[::]'
  keep_alive_enable: true
  keep_alive_idle_timeout_trigger_sec: 90
  keep_alive_max_probe_count: 3
  keep_alive_probe_interval_sec: 10
  port: 9001
  start_grpc_proxy: true
  streaming_config: {enable_output_streams: true}
hosts:
- host: localhost
  node_id: 1
  port: 29501
  walle_location: {body: 1, data_center: '1', rack: '1'}
interconnect_config: {start_tcp: true}
kqpconfig: {enable: true}
log_config: {default_level: 3, sys_log: false}
nameservice_config:
  accept_uuid: [local]
  cluster_uuid: local
pqconfig: {enabled: false}
static_erasure: none
system_tablets:
  cms:
  - info: {tablet_id: '72057594037936128'}
    node: [1]
  console:
  - info: {tablet_id: '72057594037936131'}
    node: [1]
  flat_bs_controller:
  - info: {tablet_id: '72057594037932033'}
    node: [1]
  flat_hive:
  - info: {tablet_id: '72057594037968897'}
    node: [1]
  flat_schemeshard:
  - info: {tablet_id: '72075186232723360'}
    node: [1]
  flat_tx_coordinator:
  - info: {tablet_id: '72075186232360961'}
    node: [1]
  node_broker:
  - info: {tablet_id: '72057594037936129'}
    node: [1]
  tenant_slot_broker:
  - info: {tablet_id: '72057594037936130'}
    node: [1]
  tx_allocator:
  - info: {tablet_id: '72075186232492033'}
    node: [1]
  tx_mediator:
  - info: {tablet_id: '72075186232426497'}
    node: [1]
vdisk_config:
  vdisk_kinds:
  - base_kind: Default
    config: {allow_keep_flags: false, fresh_use_dreg: true}
    kind: Log
  - base_kind: Default
    config: {hull_comp_level0_max_ssts_at_once: 2, hull_comp_sorted_parts_num: 1}
    kind: LocalMode

